### ISSUE TITLE
Clean UP & Dockerization eos935d

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos935d#6]

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda 

I've updated the workflows on this model

**Comment by HellenNamulinda** [comment]
@GemmaTuron
The actions for this model have been failing because of the python path that had been specified. [Error](https://github.com/ersilia-os/eos935d/actions/runs/5566788573/job/15075596825#step:10:8304) (`Model API eos935d:predict did not produce an output/bin/sh: 1: /usreos935d/bin/python: not found`)
This needed to be removed for the github actions to work. This plus other changes are reflected in the [PR](https://github.com/ersilia-os/eos935d/pull/7) made.
The torch version could not be changed to a higher version(>=1.7.1) supported by aarch(arm64) because the model code would need modification. So there won't be a docker image for arm64.

**Changes**
- Removed .dvc folder and files
- Install packages using pip instead of conda
- Rename run_predict to run.sh
- Updated api from predict to run
- Removed the 

The [Model Test on PR](https://github.com/ersilia-os/eos935d/actions/runs/5780840868/job/15665062339?pr=7) was successful.

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
I made a [PR](https://github.com/ersilia-os/eos935d/pull/9) so that output of the metabolites returned is a list of 10(10 columns; `Metabolite_1, Metabolite_2,..., Metabolite_10`). test: [test.csv](https://github.com/ersilia-os/eos935d/files/12311804/test.csv),
CLI output:[eos935d_cli_output.csv](https://github.com/ersilia-os/eos935d/files/12313213/eos935d_cli_output.csv), run.sh:[935d_run_output.csv](https://github.com/ersilia-os/eos935d/files/12311830/935d_run_output.csv)
```
key,input,Metabolite_1,Metabolite_2,Metabolite_3,Metabolite_4,Metabolite_5,Metabolite_6,Metabolite_7,Metabolite_8,Metabolite_9,Metabolite_10
MLBNXJTXHVBPEC-UHFFFAOYSA-N,FC(F)Oc1ccc(-c2nnc3cncc(Oc4ccc5ccsc5c4)n23)cc1,Oc1ccc(-c2nnc3cncc(Oc4ccc5c(O)csc5c4)n23)cc1,O=C(O)[C@H]1OC(Oc2ccc3ccsc3c2)[C@H](O)[C@@H](O)[C@@H]1O,Oc1cc(-c2nnc3cncc(Oc4ccc5ccsc5c4)n23)ccc1OC(F)F,Oc1cncc2nnc(-c3ccc(OC(F)F)cc3)n12,Oc1ccc(Oc2nnc3cncc(OC(F)F)n23)cc1,Oc1ncc2nnc(-c3ccc(OC(F)F)cc3)n2c1Oc1ccc2ccsc2c1,Oc1cc2ccsc2cc1Oc1cncc2nnc(-c3ccc(OC(F)F)cc3)n12,Oc1ccc(-c2nnc3c(O)ncc(Oc4ccc5ccsc5c4)n23)cc1,FC(F)Oc1ccc(-c2nnc3cncc(Oc4ccc5cc(S)sc5c4)n23)cc1,Oc1ncc(Oc2ccc3ccsc3c2)n2c(-c3ccc(OC(F)F)cc3)nnc12
AGPVLTOPROUGPQ-UHFFFAOYSA-N,FC(OC1=CC=C(C2=NN=C3C=NC=C(N32)OCC[C]4[CH]BBBBBBBBBB4)C=C1)F,Oc1cncc2ncc(-c3ccc(OC(F)F)cc3)n12,Oc1cncc2nnc(-c3ccc(OC(F)F)cc3)n12,Oc1cncc(OCC2OC(O)C(O)C2O)n1,COc1cncc2nnc(-c3ccc(OC(F)F)cc3)n12,Nc1cncc2nnc(-c3ccc(OC(F)F)cc3)n12,Oc1cncc2nnc(-c3ccc(OC(F)F)cc3)nc12,O=[As](O)OCC1=NNC(c2ccc(OC(F)F)cc2)=NC2=NC3OC3[SH]12,Oc1ccc(-c2nnc3cncc(O)n23)cc1,,
```
instead of one string(one column; Metabolites) separated by space. Also, columns `Molecule ID,SMILES` don't need to be returned(were eliminated)
```
key,input,Molecule ID,SMILES,Metabolites
MCGSCOLBFJQGHM-SCZZXKLOSA-N,Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1,molecule-0,Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1,Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](C(=O)[O-])C3)c2n1 Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](COS(=O)(=O)O)C3)c2n1 Nc1nc(NC2CC2O)c2ncn([C@H]3C=C[C@@H](CO)C3)c2n1 Nc1nc(NC2CC2)c2ncn(C3C=CC(C(=O)O)C3)c2n1 Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](C(=O)O)C3)c2n1 O=c1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](CO)C3)c2[nH]1 Nc1nc(NC2CC2)c2ncn([C@@H]3C=C[C@H](C(=O)O)C3)c2n1 Nc1nc(NC2CC2)c2ncn([C@H]3C=CC(C(=O)O)C3)c2n1 Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@@H](C=O)C3)c2n1 Nc1nc(NC2CC2)c2nc[nH]c2n1 Nc1nc(NC2CC2)c2ncn([C@H]3C=C[C@H](C(=O)O)C3)c2n1
```
Because some input molecules will have less than 10 metabolites, some columns will have empty stringths, not None as this leads to `ERROR    | Output data types are not consistent`. 

Plus, using run.sh was only accepting files with [three columns](https://github.com/ersilia-os/eos935d/blob/main/model/framework/code/process_predictions.py#L42C2-L54C1), 
```
        molID2smiles = {}
	molID2metabolites = {}
	index = 0
	drug_lines = open(input_file).read().split('\n')
	pred_counts = []
	for i in range(0,len(drug_lines)-1):
		if i!=0:
			mol_id,smiles,can_smile = drug_lines[i].split(',')
			if not check_smile(smiles):
				continue
			smiles = canonicalise_smile(smiles)
			molID2smiles[mol_id] = smiles
```
But this isn't convenient, and the can_smile column isn't needed anywhere.  As mol_ids(unique identifiers) can be assigned, the code was modified to handle that.
```
	with open(input_file, "r") as f:
		reader = csv.reader(f)
		next(reader)  # skip header
		smiles_list = [r[0] for r in reader]
	pred_counts = []
	for i in range(0, len(smiles_list)): 
		smiles = smiles_list[i]
		if not check_smile(smiles):
			continue
		smiles = canonicalise_smile(smiles)
		mol_id = f'molecule-{i}'  # Molecule numbering
```
